<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\DocPrinter.Agent\DocPrinter.Agent.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>2893dafc-5225-494c-bbd5-c724c94dd4b2</UserSecretsId>
  </PropertyGroup>

</Project>
