<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocPrinter.Core\DocPrinter.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PdfSharp" Version="6.2.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.16" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.16" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.16" />
  </ItemGroup>

</Project>
